name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: List files for debugging
      run: |
        ls -al  # List files in the root directory for debugging
        ls -al ./build  # List files in the build directory for debugging, if applicable

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./  # Root directory of your repository if static HTML files are in the root
        external_repository: nicosrp/strava-public
        publish_branch: main
