name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Adjust if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby environment and install Bundler
      run: |
        ruby -v
        echo "gem: --user-install" > ~/.gemrc
        gem install bundler --no-document --verbose
        export PATH=$HOME/.gem/ruby/$(ls $HOME/.gem/ruby/)/bin:$PATH
        export GEM_HOME=$HOME/.gem/ruby/$(ls $HOME/.gem/ruby/)
        bundle install --path vendor/bundle --verbose

    - name: Build Jekyll site
      run: |
        export PATH=$HOME/.gem/ruby/$(ls $HOME/.gem/ruby/)/bin:$PATH
        export GEM_HOME=$HOME/.gem/ruby/$(ls $HOME/.gem/ruby/)
        bundle exec jekyll build -d _site  # Jekyll outputs to _site by default

    - name: List files for debugging
      run: |
        ls -al  # List files in the root directory for debugging
        ls -al ./_site  # List files in the Jekyll build directory

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./_site  # Jekyll default build directory
        external_repository: nicosrp/strava-public
        publish_branch: main
